### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Twilight-Killer** [Infamous-Hydra/YaeMiko#151]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/debian/YaeMiko/Mikobot/__main__.py", line 102, in <module>
    imported_module = importlib.import_module("Mikobot.plugins." + module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/debian/YaeMiko/Mikobot/plugins/fun.py", line 13, in <module>
    from Mikobot.state import state
  File "/home/debian/YaeMiko/Mikobot/state.py", line 11, in <module>
    session = ClientSession()
              ^^^^^^^^^^^^^^^
  File "/home/debian/YaeMiko/YaeMiko/lib/python3.11/site-packages/aiohttp/client.py", line 294, in __init__
    loop = loop or asyncio.get_running_loop()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

**Comment by Infamous-Hydra** [comment]
Fixed
